runtime: nodejs20 # Define la versión de Node.js que usará App Engine

env: standard # Especifica que utilizarás el entorno estándar

entrypoint: node index.js

env_variables: # Variables de entorno que tu aplicación puede usar
  DB_CONNECTION_STRING: "mongodb+srv://coder53160:coder2024@tesis.9y1pk.mongodb.net/tesis"
  ACCESS_TOKEN_SECRET: "76d4ce84-e761-480a-bcc3-b402f8eaa5dc"
  REFRESH_TOKEN_SECRET: "99459a64-98dc-421c-95be-26e18f4d1b3"
  PORT: "8080" # Cambia a 8080, ya que Google App Engine utiliza este puerto por defecto

handlers: # Configuración de las rutas
  - url: /.*
    script: auto # Permite que App Engine maneje las rutas automáticamente
